### ISSUE TITLE
Create a Simple Android Application of FindIssues [FEATURE] 

### ISSUE THREAD

**Issue by Dhruvdangi03** [anand346/findissues#108]
Create a Simple Android Application of FindIssues

**Comment by anand346** [comment]
Hi @Dhruvdangi03 are you willing to work on this issue?

**Comment by Dhruvdangi03** [comment]
> Hi @Dhruvdangi03 are you willing to work on this issue?

I would love to work on it @anand346

**Comment by anand346** [comment]
I'm assigning this issue to you, kindly raise a PR when you are done 👍🏻
