### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amritregmi26** [anand346/findissues#115]
**Describe the bug**
When we click on the issue, it opens two tabs in the browser with same GitHub link

**To Reproduce**

1. Go to [this](https://www.findissues.me/search/javascript)
2. Click on any of the issues

**Expected behavior**
It should open only one tab because it leads to waste of memory if someone doesn't notice it and opens multiple issues

**Comment by anand346** [comment]
Hi @amritregmi26, everything seems good this side. Kindly recheck once with any other browser

**Comment by anand346** [comment]
Kindly check once with chrome
