### ISSUE TITLE
[FEATURE] Improve SEO of web application

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#121]
**Is your feature request related to a problem? Please describe.**
Improving SEO of web application will help other users to find the main site in more easier way.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Artal44** [comment]
Is this issue still available ?

**Comment by anand346** [comment]
Hey @Artal44, yeah this issue is still open

**Comment by Artal44** [comment]
I’ll try starting on this if possible.

**Comment by anand346** [comment]
well I don't know much about SEO, but yeah improving meta tags and optimizing assets can increase the SEO I guess

**Comment by Artal44** [comment]
For the improvements I would like to make, I have 3 different assets I would like to improve : Meta tags, header tags and image alt text. I have made some analysis of the app and I think it won't be that difficult to implement. Is it okay for you?

**Comment by anand346** [comment]
yeah, that would be good

**Comment by Artal44** [comment]
I made some changes in the keywords and added meta tags in the _app.js file. I also change alt tags of some images to add some precision.

**Comment by Artal44** [comment]
But it seems i can't make a push request into the branch i created

**Comment by Artal44** [comment]
Could you assign me the task so that I can push?

**Comment by anand346** [comment]
Sure

**Comment by Artal44** [comment]
Hi @anand346, I modified some scripts to be able to automatically generate a site-map for the website and I also added the link of the site-map in the header of the different pages.

**Comment by anand346** [comment]
fixed in #136
