### ISSUE TITLE
[FEATURE]: Add Pagination or Infinite scrolling effect

### ISSUE THREAD

**Issue by basavarajakj** [anand346/findissues#139]
Add Pagination or Infinite scrolling effect so UX will become smooth and restrict number of data to show instead of flooding all the data to UI.

**Describe the solution you'd like**
We can use ``` Tanstack react query``` to achieve this

**Comment by Ved-panchal** [comment]
Is this issue is still open?

**Comment by anand346** [comment]
Hi @basavarajakj would you like to work on this issue?

**Comment by basavarajakj** [comment]
@anand346 I am on a Trip, I can't know.

**Comment by anand346** [comment]
Oh ok
