### ISSUE TITLE
[FEATURE] Scroll Indicator

### ISSUE THREAD

**Issue by Priya434** [anand346/findissues#141]
The left sidebar and main sections lack a visible sidebar which sometimes gives a perception that no more tags repos or content might be visible.

I think that a sidebar or a visible indicator showing that the user can scroll to find more content would be beneficial.

<img width="198" alt="image" src="https://github.com/anand346/findissues/assets/92980244/85e20486-47c1-4e5d-b116-4a241aa95dc2">

<img width="199" alt="image" src="https://github.com/anand346/findissues/assets/92980244/55382de4-9b52-4001-994d-420a62f8d2a9">

**Comment by anand346** [comment]
hi @Priya434, would you like to work on this issue?

**Comment by Priya434** [comment]
> hi @Priya434, would you like to work on this issue?

No @anand346 , I'm unable to work on this issue at the moment.

**Comment by tusharpasricha** [comment]
Hi, Please assign this to me.

**Comment by rupali-codes** [comment]
> Hi, Please assign this to me.



> Hi, Please assign this to me.

You're assigned. Please let us know if you need any assistance.
