### ISSUE TITLE
back to top not showing on active repos [BUG]

### ISSUE THREAD

**Issue by FazeenIjaz** [anand346/findissues#142]
**Describe the bug**
Back to top button is not being shown on active repos.

**To Reproduce**

1. Go to 'https://www.findissues.me'
2. Click on 'active repos'
3. Scroll down to See error.

**Comment by Sahillather002** [comment]
![image](https://github.com/anand346/findissues/assets/72077931/78492903-aefd-40ff-9fbc-ac2fc667c0c6)
yes 
pls assign issue

**Comment by anand346** [comment]
fixed in #145
