### ISSUE TITLE
[BUG] JS issues search is showing 404 error 

### ISSUE THREAD

**Issue by FazeenIjaz** [anand346/findissues#143]
**Describe the bug**
(https://www.findissues.me/search/javascript) is showing 
![image](https://github.com/anand346/findissues/assets/144797618/92b729bf-bf04-4da5-bc04-7af63e852560)

**To Reproduce**

1. Go to [find issues](https://www.findissues.me/)
2. Click on javascript in left sidebar
3 See error

**Screenshots**

**Comment by dhruvsethi708** [comment]
I have just tested the JavaScript search functionality on my system, and it seems to be working fine without any errors.
<img width="938" alt="Screenshot 2024-02-08 001031" src="https://github.com/anand346/findissues/assets/74965209/7b070856-f455-47bb-b4ad-9bd953b6702c">

**Comment by CHINMAYHACKERHACKER** [comment]
pls close this issue if its working
