### ISSUE TITLE
[BUG] Javscript tag showing error

### ISSUE THREAD

**Issue by Sahillather002** [anand346/findissues#144]
![image](https://github.com/anand346/findissues/assets/72077931/4a6f6051-ffec-4533-976f-f15b8ecad16c)

**Comment by priyanshu-434** [comment]
Could you provide any reproducible steps?
I checked but couldn't find the bug in the production site or my local repo.

**Comment by Sahillather002** [comment]
ya its working fine now , maybe some issue that time only !

**Comment by Sahillather002** [comment]
ok
