### ISSUE TITLE
[FEATURE]Ability to select multiple filters including both languages and tags

### ISSUE THREAD

**Issue by abdullahshahid95** [anand346/findissues#147]
**Title
Ability to select multiple filters including both languages and tags**

**Description**
Currently, we can select only one option from filters, a programming language or a tag. How about giving user the ability to select more than one options from filters. For example, a user can select JavaScript, Go in languages and good-first-issue in tags, and get search results accordingly.

**Comment by rupali-codes** [comment]
@abdullahshahid95 do you want work on this issue?

**Comment by abdullahshahid95** [comment]
Yes, I would like to work on this :-)

**Comment by anand346** [comment]
Hi, this issue has conflicts with the github API terms and policies. Closing this issue now as we have limits to send request on github API on hourly basis.
