### ISSUE TITLE
[FEATURE] Add Light mode option

### ISSUE THREAD

**Issue by EleniVasilaki** [anand346/findissues#150]
Is your feature request related to a problem? Please describe.
Adding a light theme; the lack of a light mode option may inconvenience users who prefer lighter color schemes

Describe the solution you'd like
Add theme changing functionality for light mode, alongside the existing dark mode

I would like to work on this issue with @sofiacharatsi if possible

**Comment by anand346** [comment]
Hi @EleniVasilaki , sure I'm assigning this issue to you.
