### ISSUE TITLE
[BUG] The sorting dropdown is not being shown on the "active repos" page

### ISSUE THREAD

**Issue by sofiacharatsi** [anand346/findissues#152]
**Describe the bug**

The sorting dropdown is not being shown on the "active repos" page.

**To Reproduce**

1. Go to 'https://www.findissues.me'
2. Click on 'Active Repos'
3. See error 

**Expected behavior**

The sorting dropdown should be visible.

**Screenshots**

![Screenshot 2024-06-07 224049](https://github.com/anand346/findissues/assets/117755881/45817d68-bd1a-43a2-8ca1-a05504f7b703)
![Screenshot 2024-06-07 224058](https://github.com/anand346/findissues/assets/117755881/e7c11fc3-1a71-4724-8ef4-a4e641aded44)
![Screenshot 2024-06-07 224112](https://github.com/anand346/findissues/assets/117755881/037396d9-dc7f-4586-8073-5a74ca946d82)

I would really like to work on this issue!

**Comment by anand346** [comment]
fixed in #145
