### ISSUE TITLE
[BUG] Web application link in the README file is wrong

### ISSUE THREAD

**Issue by itayfry** [anand346/findissues#158]
**Describe the bug**
The link in Get started at the end of the sentence "To begin go to the web application: [FindIssues](https://www.findissues.me/)" leads to a domain which doesn't seem relevant anymore and should be replaced by the vercel link

**To Reproduce**
click on the FindIssues link under get started

**Expected behavior**
Should open https://findissues.vercel.app

**Comment by itayfry** [comment]
To be honest my main motivation to opening this issue is to understand if the repo is active and valid for contributions.
I have a forked repo with a branch ready for the fix if relevant:
https://github.com/itayfry/findissues/compare/main...fix-README-web-app-link

And if so, I have a couple of improvements in mind for the search functionality that I'd like to open issues for and contribute as well.

**Comment by anand346** [comment]
Hi @itayfry you can start working on this issue.
