### ISSUE TITLE
[FEATURE] Unable to Select Multiple Language Tags at the Same Time

### ISSUE THREAD

**Issue by fahadshahbaz** [anand346/findissues#159]
### ➡️ Is your feature request related to a problem? Please describe.
Yes, the issue is that I can't select more than one language tag at a time when searching for issues. This makes it difficult to find issues that involve multiple technologies, like HTML and CSS or JavaScript together.

### ➡️ Describe the solution you'd like
I’d like to see a multi-select option for language tags, allowing users to filter issues by choosing multiple tags at the same time. This would make it easier to find issues requiring a mix of skills.

### ➡️ Describe alternatives you've considered
An alternative could be a search box where users type in multiple languages separated by commas, but a multi-select dropdown or checkbox would be more straightforward.

### ➡️ Additional context
Adding a multi-select feature would improve the user experience by making it easier to find issues that align with multiple skill sets.

**Comment by coder483** [comment]
would like to work on this

**Comment by krishp007** [comment]
Please assign me this issue, I would be glad to work on this

**Comment by arbazahmed07** [comment]
Pls assign me this @fahadshahbaz

**Comment by Dhruvnotfound** [comment]
would even be better if u let us type our own tags other than the basic ones?

**Comment by anand346** [comment]
We don't need this feature
