### ISSUE TITLE
[DOCS] create CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by rupali-codes** [anand346/findissues#17]
Adding CONTRIBUING guidelines would help contributors to contribute effectively to the project.

I would like work on this issue :)

**Comment by anand346** [comment]
Sure @rupali-codes , I'm assigning this to you ;)

**Comment by rupali-codes** [comment]
> Sure @rupali-codes , I'm assigning this to you ;)

Thank you. I'll raise the PR as soon as i can :)

**Comment by anand346** [comment]
Issue got fixed
