### ISSUE TITLE
[BUG] Found security Issue

### ISSUE THREAD

**Issue by rupali-codes** [anand346/findissues#20]
**Describe the bug**
There's a security voluntary in your application, when I hit [this](https://findissues.vercel.app/search/dsjsjdskjdksd) its showing very unclear results, and its hard to see for which language its showing these results. 

**Expected behavior**
It is suppose to show an error page

**Screenshots**
![image](https://github.com/anand346/findissues/assets/78981177/c3b33c2f-8f93-4b68-ac36-08a90f45ffdf)

**Additional context**
I want to work on this issue :)

**Comment by anand346** [comment]
Hi @rupali-codes are you willing to work on this issue?
