### ISSUE TITLE
[OTHER] Change the 'Issues Result' title to 'All Unassigned Issues 👇'

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#21]
**Title**
Change the `Issues Result` title to `All Unassigned Issues 👇`

**Description**
When you search issues of a particular language then on the middle part the title of `Issues Result` should be changed to `All Unassigned Issues 👇`

**Screenshots** (optional)
![image](https://github.com/anand346/findissues/assets/64061582/15cd3a67-547d-4a81-89e0-1ac3dead1b6c)

For more accuracy kindly refer to the above screenshot

**Comment by rahuld2000** [comment]
I would like work on this issue :)

**Comment by hiteshd987** [comment]
Hi @anand346 I have changed the title. Can you please review it?
