### ISSUE TITLE
[OTHER] Add PR Template

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#27]
**Title**
Add a pull request template

**Description**
Currently there is no pull request template in this repo coz of this whenever a contributor tries to make a pull request he/she may get confused about what to include and what to not in the PR. By adding a pull request template we can tell other contributors what are the expected details of a PR.

In the PR template following section must be included:
1. Fixed Issue
2. Proposed Changes
3. Screenshots
4. Notes for reviewers

**Comment by rahul9852-dot** [comment]
Hi @anand346 I have raised PR for above the above issues by covering all the points which you have mentioned. If possible could look into that.

**Comment by anand346** [comment]
Ok, will check and merge soon

**Comment by anand346** [comment]
Hi @rahul9852-dot , can you please give you PR link here

**Comment by rahul9852-dot** [comment]
@anand346  [link](https://github.com/rahul9852-dot/findissues/pull/1/files)

**Comment by anand346** [comment]
Hi @rahul9852-dot, you need to make a pull request in the main branch of this repo. Currently you have created the pull request in your forked main branch

**Comment by rahul9852-dot** [comment]
Sorry @anand346 I have't checked properly can you check this [link](https://github.com/anand346/findissues/pull/36)

**Comment by anand346** [comment]
Fixed in #36
