### ISSUE TITLE
[FEATURE] To add theme changing functionality

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#28]
**Is your feature request related to a problem? Please describe.**
Adding a theme changing functionality

**Describe the solution you'd like**
Add a theme changing functionality can increase the UX of the web app. Other developers and contributors can contribute different themes.

**Comment by lokeshvasnik** [comment]
You mean to say multiple themes or just the dark mode.

**Comment by adityarawat1223** [comment]
can i work on this ?

**Comment by anand346** [comment]
Hi @adityarawat1223 , yeah if you are willing to work on it. Go ahead

**Comment by SiddharthaKR** [comment]
Can you assign this to me? @anand346

**Comment by adityarawat1223** [comment]
I am already working on this @SiddharthaKR

**Comment by SiddharthaKR** [comment]
oh as in assignees it showed no one assigned so i looked into no problem

**Comment by rishuxd** [comment]
Hey @anand346 , it has been 3 weeks since this issue is assigned and it is still open, can I work on it?

**Comment by anand346** [comment]
Hi @adityarawat1223 are you still working on it?

**Comment by zhitianguan** [comment]
Hi @anand346, it's been 1 month since the previous comment, can I work on this issue?

**Comment by anand346** [comment]
Hi @zhitianguan, I'm assigning this issue to you

**Comment by anand346** [comment]
fixed in #153
