### ISSUE TITLE
[FEATURE] Make the background blurry when opening sidebar (mobile view)

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#29]
**Is your feature request related to a problem? Please describe.**
Making the background blurry whenever the sidebar opens. 

**Describe the solution you'd like**
Currently when sidebar opens, the background is not blurred which is not providing a good user experience. Making the background blur whenever sidebar opens will help users to just focus on the sidebar content nowhere else.

**Comment by LOGESH-B** [comment]
Hii @anand346 
I am willing to work on this.can I get Assigned?

**Comment by bhalerao-2002** [comment]
Ok @anand346, I had reviewed the code and understand your problem, after opening sidebar its distracting and not feeling good.
Assign me this issue under Hacktoberfest 2023, I will try to resolve it far better way.

**Comment by anand346** [comment]
Hi @bhalerao-2002 , I'm assigning this issue to you. Kindly raise a PR when you are done 👍🏻

**Comment by anand346** [comment]
Hi @bhalerao-2002 , is there any update on this issue?

**Comment by bhalerao-2002** [comment]
Yes, I am trying to do better work, I will raise PR after 1 Oct, as with respect to, it will be counted for Hacktoberfest

**Comment by Basavarajakjbasuu** [comment]
Thank you @anand346 and That not problem let @bhalerao-2002  can work Its my permillage to contribute in OS.

**Comment by anand346** [comment]
Thanks @Basavarajakjbasuu, I really appreciate your efforts. Please feel free to work on any other issue, thanks.

**Comment by KrishavRajSingh** [comment]
is this open?

**Comment by SiddharthaKR** [comment]
Hello i can help by resolving this issue can you assign it to me @anand346

**Comment by anand346** [comment]
Fixed in #35
