### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Basavarajakjbasuu** [anand346/findissues#31]
## When I click on tags its not highlighting

**To Reproduce**
1. Go to homepage
2. Click on  any tags Ex. good-first-issues
3. See error

**Expected behavior**
It should highlight 

**Screenshots**
![image](https://github.com/anand346/findissues/assets/97227305/8c778743-3a99-462e-8845-60e07ff03eeb)

**Additional context**
Feel free to ask further doubts

**Comment by Basavarajakjbasuu** [comment]
I am facing problem in setuping repo in local environment, Could you please any one help me. I am new to open source

**Comment by anand346** [comment]
Hey @Basavarajakjbasuu , you can create github PAT ( personal access token ) from developer settings in your profile

**Comment by Basavarajakjbasuu** [comment]
Thank you for ur reply I have setup already.
