### ISSUE TITLE
[Feat]:when click outside of sidebar it should close

### ISSUE THREAD

**Issue by Basavarajakjbasuu** [anand346/findissues#39]
Please add UX When click on outside of sidebar nothing is happening Please add a feature to close it

### Source
1.  Click on URL
2.  Go to home page
3.  minimise the screen and click hamburger menu 
4. click to outside of side bar

**Comment by Basavarajakjbasuu** [comment]
Please add ```Hacktoberfest``` label,  I would like to work on this issue I have Experience is this could you please to assign to me😂😂.

**Comment by anand346** [comment]
Hi @Basavarajakjbasuu , I'm assigning this issue to you. Kindly raise a PR when you are done 👍🏻

**Comment by SAGARSINGH-1** [comment]
@anand346 if @Basavarajakjbasuu is not working or not able to solve this issue please assign me this issue.

**Comment by Basavarajakjbasuu** [comment]
I am working, sure I will come up with PR

**Comment by Basavarajakjbasuu** [comment]
@anand346  Could you please add ```hactoberfest-accepted``` label It will help to verification 😁😁

**Comment by anand346** [comment]
Oh I'm sorry, fogot to add the label
