### ISSUE TITLE
[Other] Change the landing page title to "FindIssues"

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#40]
**Title**
Change the landing page title to "FindIssues"

**Description**
Currently when you visit [FindIssues](https://www.findissues.me) then you can see the page title is `findissues.me`. But the page title of landing page should be only `FindIssues`.

**Screenshots** 
![image](https://github.com/anand346/findissues/assets/64061582/6540a20b-6700-4a00-a3b6-48b6d11b434c)

**Comment by Harsh97x** [comment]
I want to fix it. Assign me please. Thanks

**Comment by anand346** [comment]
Hi @Harsh97x , I'm assigning this issue to you. Kindly raise a PR when you are done 👍
