### ISSUE TITLE
[SEO] Add open graph (og) and twitter meta tags

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#41]
**Title**
Add open graph and twitter meta tags for all the pages.

**Description**
Adding Open graph (og) and twitter meta tags helps in improving the SEO of web application. Currently there are no meta tags applied in any pages of the application due to which the SEO rank of the web application is very low. Apply meta tags to every page of the web application.

**Comment by anand346** [comment]
Hi @Mridul2820, sure I'm assigning this issue to you. Kindly raise a PR when you are done 👍

**Comment by Mridul2820** [comment]
Hi @anand346 , I have raised the PR

**Comment by anand346** [comment]
closing this issue, as it is fixed in #45
