### ISSUE TITLE
[FEATURE] Add Back-to-top button

### ISSUE THREAD

**Issue by rupali-codes** [anand346/findissues#43]
**Is your feature request related to a problem? Please describe.**
I want to add back-to-top button on the result page, as user scrolls down then it gets annoying to scroll to top for other issues. 

**Describe the solution you'd like**
Adding back-to-top button will lead to a great user experience.

**Comment by anand346** [comment]
Hi @rupali-codes , I'm assigning this issue to you. Kindly raise a PR when you are done 👍

**Comment by rupali-codes** [comment]
> Hi @rupali-codes , I'm assigning this issue to you. Kindly raise a PR when you are done 👍

sure thing, thanks :)

**Comment by MurtazaShikari** [comment]
@anand346 is this issue still open can u assign this to me?

**Comment by rupali-codes** [comment]
> @anand346 is this issue still open can u assign this to me?

I'll be working on this issue, just got a little busy, you can checkout the other open issues

**Comment by Nupur19nj** [comment]
Hey if it's not yet done can you please assign this to me!

**Comment by anand346** [comment]
@rupali-codes are you still working on it?

**Comment by anand346** [comment]
I'm assigning this issue to @Nupur19nj

**Comment by anand346** [comment]
Hi @Nupur19nj, kindly raise a PR when you are done 👍

**Comment by Nupur19nj** [comment]
sure! Thanks

**Comment by Peteredwardj** [comment]
Hi @Nupur19nj are you still working on this issue? I'm interested in working on this

**Comment by anand346** [comment]
Hi @Peteredwardj, I'm assigning this issue to you
