### ISSUE TITLE
[FEATURE] Filtering for tags and languages

### ISSUE THREAD

**Issue by SpatzlHD** [anand346/findissues#46]
I think it would be a great addition to the website if you could filter for tags and languages at the same time. Because at the moment you can only filter for one at the time. But let's say I want to find a JavaScript project that accepts contributions for hacktoberfest I have to either Filter for JavaScript and then try to find a repository with the hacktoberfest tag or I have to filter for the hacktoberfest tag and then try to find a project which is written in js.

I can work on this if you want.

**Comment by SAGARSINGH-1** [comment]
Hey @SpatzlHD ,

Thank you for the proposal to implement idea to the project. I'm excited about the opportunity to contribute to the project and explore this idea further.

Before I confirm my ability to contribute effectively, I would like to take some time to thoroughly review the codebase and gain a deeper understanding of the project's structure and requirements. This will help me ensure that I can make a valuable contribution that aligns with the project's goals.

**Comment by anand346** [comment]
Hi @SpatzlHD, your idea is great but to implement it we need to redesign the UI of leftsidebar/navbar such that the user can select with which tag and language he/she wants to get the issues result. Something like dropdown we can implement what say?

**Comment by SpatzlHD** [comment]
@anand346 I don't quite understand what you want to achieve with a drop-down menu tbh. My idea would be to just not reset the selected filter every time the user clicks on a new one. And just show results based on all filters selected. Maybe even extend this concept so you can filter for multiple languages at the same time. And then maybe introduce a reset button in the nav bar that allows you to reset all filters at the same time.

**Comment by anand346** [comment]
Sounds interesting, that would be a great approach

**Comment by anand346** [comment]
Hi @SpatzlHD, I'm assigning this issue to you. Kindly raise a PR when you are done 👍

**Comment by SpatzlHD** [comment]
> Hi @SpatzlHD, I'm assigning this issue to you. Kindly raise a PR when you are done 👍

Thanks! I will work on this on the weekend so in something like three days.

**Comment by SpatzlHD** [comment]
@anand346 after taking a closer look at this I noticed that I probably have to rewrite some of the logic of how the application handles routing and the difference between languages and tags... So I hope that this is ok for you

**Comment by anand346** [comment]
Yeah, there can be a change in the routing logic of the web app. Actually an issue might arise with this feature.. the Github API allows only `5000 requests per hour`, and if a single user fetch issues by combining different tags and languages at the same time then the limit might get exhausted. Currently there are `two PATs` are being used in the web app to fetch issues and we are fetching only 30 issues of every language and tag in an interval of 10 minutes using that two PATs.

**Comment by SpatzlHD** [comment]
> Actually an issue might arise with this feature.. the Github API allows only 5000 requests per hour, and if a single user fetch issues by combining different tags and languages at the same time then the limit might get exhausted.

That is true.

> we may use Github Actions to fetch issues every 10 minutes and store in a json file.

That would actually simplify things significantly. Because then I would only need to filter the JSON file for the tags and languages and don't need to generate new request url's for all selected filters.

**Comment by SpatzlHD** [comment]
As I already mentioned [here](https://github.com/anand346/findissues/issues/48#issuecomment-1750347285) I think it would be a good idea to have your own backend for something like this but for now we can probably get away with GitHub actions but because I didn't work with vercel that much does vercel have to build a new version of the deployment every time the JSON file is updated or can we somehow fetch the data from a JSON file hosted on GitHub on the client? Is it possible to programmatically get the raw file view? Or is this somehow protected from accessing it?

**Comment by anand346** [comment]
>That would actually simplify things significantly. Because then I would only need to filter the JSON file for the tags and languages and don't need to generate new request url's for all selected filters.

yeah, if you have some reference on how to generate data with github actions and store in a file then kindly send me the link it would be helpful to me. thanks

**Comment by anand346** [comment]
> As I already mentioned [here](https://github.com/anand346/findissues/issues/48#issuecomment-1750347285) I think it would be a good idea to have your own backend for something like this but for now we can probably get away with GitHub actions but because I didn't work with vercel that much does vercel have to build a new version of the deployment every time the JSON file is updated or can we somehow fetch the data from a JSON file hosted on GitHub on the client? Is it possible to programmatically get the raw file view? Or is this somehow protected from accessing it?

The idea is we'll use Github Actions to fetch and store issues every 10 minutes in a json file and will render all the issues from that json file in the web app. Currently we are fetching issues every 10 minutes with the help of `getStaticProps()`. But after implementing Github Actions there will be no need of `getStaticProps`. 

And for the active repo list we'll make another json file and every time the authenticated user on our web app submit a new repo url a new PR will be created from his/her account to the main repo and once everyday I'll review all the submitted url PRs and merge it so that the submitted repo url get stored in that json file

Both Active repo list functionality and storing issues with Github Actions functionality are separate from each other. Hope it is clear

**Comment by SpatzlHD** [comment]
> The idea is we'll use Github Actions to fetch and store issues every 10 minutes in a json file and will render all the issues from that json file in the web app. Currently we are fetching issues every 10 minutes with the help of getStaticProps(). But after implementing Github Actions there will be no need of getStaticProps.

But then we still have the problem of having to re-deploy to vercel every 10 minutes when the JSON file updates... Or am I wrong?

**Comment by SpatzlHD** [comment]
@anand346 can you please verify my assumption about the JSON file?

**Comment by anand346** [comment]
Hi @SpatzlHD, we can apply configuration to vercel that if changes made to the json file then the project should not be rebuild.

Check it for example: https://stackoverflow.com/questions/70615014/how-to-prevent-vercel-from-deploying-master-branch-if-only-readme-md-is-changed

**Comment by SpatzlHD** [comment]
> Hi @SpatzlHD, we can apply configuration to vercel that if changes made to the json file then the project should not be rebuild.
> 
> Check it for example: https://stackoverflow.com/questions/70615014/how-to-prevent-vercel-from-deploying-master-branch-if-only-readme-md-is-changed

So we would need to still fetch the file and not bundle it inside the code? But instead of fetching the GitHub API we just fetch the content of the file hosted on GitHub?

**Comment by anand346** [comment]
yeah, that's true

**Comment by anand346** [comment]
> > Hi @SpatzlHD, we can apply configuration to vercel that if changes made to the json file then the project should not be rebuild.
> > Check it for example: https://stackoverflow.com/questions/70615014/how-to-prevent-vercel-from-deploying-master-branch-if-only-readme-md-is-changed
> 
> So we would need to still fetch the file and not bundle it inside the code? But instead of fetching the GitHub API we just fetch the content of the file hosted on GitHub?

yeah that's true
