### ISSUE TITLE
[FEATURE] Functionality to make active repos list available to open-source contributors

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#48]
**Is your feature request related to a problem? Please describe.**
Open-source contributors are always in search for those repos which are active and which accept PRs as soon as possible. But they face difficulties in searching for those "active repos".

**Describe the solution you'd like**
To make open-source contributors aware of available active repos, the idea is to add a functionality to login with Github and then open-source enthusiasts can submit the link of active repo directly through the web application. This will help other contributors in searching for active repos and making contributions.

Here the term "active repos" refers to those repos which are **updated in last 3 - 5 days** and the **submitting user must have contributed to that repo**.

The approach might be this way:

1. Adding "Login with Github" button in the navbar.
2. User will login with their account.
3. After login user will get a form inside a popup to enter the repo link and hit submit button.
4. An PR will be created through his account to the original repo of FindIssues after submission of form.
5. After manually reviewing the PR and the repo link which is submitted, PR will get merged.
6. And so the submitting user will be counted as a contributor in FindIssues.

**Describe alternatives you've considered**
None

**Additional context**
Any kind of suggestions will be highly appreciated.

**Comment by KrishavRajSingh** [comment]
1. where will be the link stored?
2. I think instead of a  pop-up we should create a button to add links as a single user can give multiple links.

**Comment by anand346** [comment]
1. The link will be stored in a json file
2. yep for better UX when the user will click on "add active repo" button then the modal will open and inside the modal there will be form containing an input field to accept the link and a submit button, what say?

**Comment by SpatzlHD** [comment]
If you are planing to add more "user" Features I think it would be way easier to just build your own backend instead of using github for everything. because I don't think its the way to go to just rebuild the vercel project everytime someone adds a link. And this would also be true for #46 as building the vercel instance new every 10 minutes isnt a good idea in my opinion.

**Comment by SpatzlHD** [comment]
Or am i missing something about your idea or the vercel deployment pipeline

**Comment by SpatzlHD** [comment]
And also from a security standpoint (correct me if I am wrong) I think it's not really best practice to do user authentication on the client... Especially not if you are handling sensitive information like GitHub user access tokens

**Comment by anand346** [comment]
> If you are planing to add more "user" Features I think it would be way easier to just build your own backend instead of using github for everything. because I don't think its the way to go to just rebuild the vercel project everytime someone adds a link. And this would also be true for #46 as building the vercel instance new every 10 minutes isnt a good idea in my opinion.

yeah.. you are right, but I'll not deploy a new instance everytime there is a new link submitted. Instead I'll review all the PRs once everyday may be in the morning and then will merge the PRs

**Comment by anand346** [comment]
> And also from a security standpoint (correct me if I am wrong) I think it's not really best practice to do user authentication on the client... Especially not if you are handling sensitive information like GitHub user access tokens

Yeah authentication on the client side is not recommended, will come up with some idea.

**Comment by anand346** [comment]
I've changed the idea now, users don't need to login with their account. user can just click on add repo button which will redirect him/her to the contributions file of this repo where he/she will get to know how he/she can add active repo in a json file and raise a PR. Then everyday the maintainer need to merge that PR and there will be settings applied to vercel that if any changes made to that particular json file then the project should not be rebuilded. In this way we'll get the active repos in a json file and we can render the relative information of all the repos like stars, forks, updated_time etc. to the user. What say?

**Comment by anand346** [comment]
Closing this issue as it is fixed in #60
