### ISSUE TITLE
[FEATURE] Update the time of issue creation on runtime

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#49]
**Is your feature request related to a problem? Please describe.**
Currently there is a timestamp in the right bottom of issue card of the issue list which shows the time of issue creation. But it is not getting updated with the time. In the below screenshot the time is showing "6 minutes ago" but it is not getting updated along with the time.

![image](https://github.com/anand346/findissues/assets/64061582/724a5728-c78f-4998-9098-6cbba65501fb)

**Describe the solution you'd like**
To implement a functionality which can update the time of issue creation along with the time. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by lokesh-veerappan-47** [comment]
Looks pretty straightforward. I can do a quick PR

**Comment by lokesh-veerappan-47** [comment]
@anand346 Check out the PR https://github.com/anand346/findissues/pull/50

**Comment by anand346** [comment]
This issue is fixed in PR #50, thanks to @lokesh-veerappan-47's impactful contribution
