### ISSUE TITLE
[FEATURE] make the entire issue card clickable and add hover to time since issue creation

### ISSUE THREAD

**Issue by SpatzlHD** [anand346/findissues#52]
**Is your feature request related to a problem? Please describe.**
When clicking anywhere on the issue card expect the title or the repo link nothing happens. But the hover efect indicates otherwise.

**Describe the solution you'd like**
Make it so that if you click anywhere on the card (blue marked in the image) not only the title you will be redirected to the issue page and if you click on the repo link (marked red) you will be redirected to the repo page. And it would also be great that if you hover over the time it would show the exact time the issue was created and not only the time elapsed since it was created.

**Additional context**
![image](https://github.com/anand346/findissues/assets/79466158/4e85da55-8bd2-4120-9ff5-aa5394ee22ac)

**Comment by anand346** [comment]
@SpatzlHD, would you like to work on it?

**Comment by SpatzlHD** [comment]
> @SpatzlHD, would you like to work on it?

Yes. That shouldn't take much time and is a good start for me to work a bit more with the project before starting #46

**Comment by anand346** [comment]
ok I'm assigning this to you

**Comment by SpatzlHD** [comment]
@anand346 I raised a pr #55

**Comment by anand346** [comment]
This issue is fixed in #55
