### ISSUE TITLE
[BUG] Inconsistent time displayed on the issue cards when compared to github issue pages

### ISSUE THREAD

**Issue by lokjaw** [anand346/findissues#54]
The time elapsed that is displayed in issues card is inconsistent with what github themselves show on their issues page 

**To Reproduce**

1. Search for issues in the app
2. Check the time elapsed text displayed on some of the issue cards
3. Open the respective issues page on github and check the time elapsed that is displayed there
4. Sometimes you'll see inconsistency

**Additional context**
The calculation logic for time elapsed since issue creation is done through a utility function from moment.js which is inconsistent with github's calculation on the same. We have to implement our own logic for this or find a better package or utility.

**Comment by lokjaw** [comment]
@anand346 this PR https://github.com/anand346/findissues/pull/53 will close this issue.

**Comment by anand346** [comment]
Closing this bug as it is fixed in #53
