### ISSUE TITLE
Add Contributers section in the README.md file

### ISSUE THREAD

**Issue by kaustab28** [anand346/findissues#56]
I want to add the list of contributors in the Readme.md file.

And also add a "back to top" button at the bottom of readme which will scroll to top on clicking.
Could you please assign it to me under Hacktoberfest?

**Comment by anand346** [comment]
Hi @kaustab28 sure I'm assigning this issue to you. Kindly raise a PR when you are done

**Comment by kaustab28** [comment]
Hey @anand346  ,
Raised a PR. Kindly check.

**Comment by anand346** [comment]
This issue is fixed in #57
