### ISSUE TITLE
Issues of Repo having 0 stars and forks are showing in the issues result.

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#6]
while searching for issue in a particular prg. lang , issues of repo having 0 stars and forks are showing in issues result tab .

It should show issues of those repo which are having alteast >= 100 stars or forks

**Comment by KrishavRajSingh** [comment]
would love to wok on this issue, if u assign me.

**Comment by anand346** [comment]
Hi @KrishavRajSingh, if you are willing to work on this. Go ahead

**Comment by anand346** [comment]
Hi @xinxin-hu, yeah this issue is still open. You can work on it

**Comment by KrishavRajSingh** [comment]
Go for it

**Comment by anand346** [comment]
Hi @xinxin-hu I'm assigning this issue to you
