### ISSUE TITLE
[OTHER] Add active repo on FindIssues

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#62]
**Title**
**Add active repo on FindIssues web application**

**Description**
_Note: You don't have ask permission to start solving the issue or get assigned, since these issues are supposed to be always open for new contributors. So you can just simply start working with the issue right away!_

In this issue you have to just **add any active github repo link** on [FindIssues](https://findissues.me) web application and any beginner open-souce contributor can do that very easily by following [these instructions](https://github.com/anand346/findissues/blob/main/list-active-repo.md), fulfilling the mentioned `criteria` you can add active github repo and make your **hacktoberfest contribution** very easily.

Feel free to ask any questions here if you have some problems!

**Also, kindly give this project a star to enhance its visibility for new developer**

**Comment by harshjais369** [comment]
@anand346 hey, I've made the pull request on this issue.. Kindly do check it at your convenience.
