### ISSUE TITLE
Adding a Language "Shell" in Basic Search.

### ISSUE THREAD

**Issue by sangdeepganvir** [anand346/findissues#65]
**Is your feature request related to a problem? Please describe.**
There is not a search available for shell projects. So i want to add a language shell in basic search.

**Describe the solution you'd like**
I want to add a language shell in basic search.

@anand346 @Mridul2820 @lokjaw @rahul9852-dot @Harsh97x  Please assign me this under hacktoberfest 2023.

**Comment by anand346** [comment]
Hi @sangdeepganvir, I'm assigning this issue to you. Kindly raise a PR when you are done 👍

**Comment by anand346** [comment]
it is fixed in #71
