### ISSUE TITLE
[BUG] Clicking on a issue title opens two tabs for the same issue github page

### ISSUE THREAD

**Issue by slayeh17** [anand346/findissues#76]
**Describe the bug**
When clicking on the title of the issue two tabs open for the same issue.

**To Reproduce**
From the list of issues found click on the title of any issue.

1. Go to 'https://www.findissues.me/search/hacktoberfest'
2. Click on 'Title of an issue'
3. See error (Two tabs open with the same issue GitHub page)

**Expected behavior**
Clicking on the title should open 1 tab

**Screenshots**
Video: [Screencast from 10-15-2023 07:31:23 AM.webm](https://github.com/anand346/findissues/assets/104914725/9b0bd037-d425-41e8-8665-61f1def0d204)

**Comment by slayeh17** [comment]
Also, can I work on this issue?

**Comment by anand346** [comment]
Hey @slayeh17 kindly recheck once, everything seems good this side.

**Comment by slayeh17** [comment]
Yeah, I just checked it in Chrome seems to be working fine but doesn't work in Firefox (Rechecked many times). 😅

Sorry, probably something on my end. Closing the issue.
