### ISSUE TITLE
[BUG] Make 'Active repos' button highlight 

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#79]
**Describe the bug**
Currently on hitting `https://www.findissues.me/active-repos` `Active repos` button does not highlight in **desktop or mobile view** like the respective language or tag highlights on hitting /search/:lang or /search/:tag

**To Reproduce**

1. Go to https://www.findissues.me/active-repos and see that the option of `Active repos` button does not highlight in desktop or mobile view

**Expected behavior**
The `Active repos` button should be highlighted whenever the user hits **https://www.findissues.me/active-repos** on the both desktop and mobile view like the respective language or tag highlights on hitting /search/:lang or /search/:tag

**Screenshots**
![image](https://github.com/anand346/findissues/assets/64061582/2b9ea389-f504-4c0a-9606-d5364cd4faaf)
![image](https://github.com/anand346/findissues/assets/64061582/c38cb6d3-bba9-4382-880b-1fee5fea1c87)

**Additional context**
N/A

**Comment by DarkSoul26** [comment]
Hey @anand346, let me take a look into this

**Comment by IbraheemHaseeb7** [comment]
hey @anand346 

On desktop it seems like it's working just fine...but on mobile view i can see it does not work.....Can you confirm the issue?

**Comment by anand346** [comment]
Maybe because of the new environment variable which I've added few days back but forgot to update in the contributing.md file. Will update you once the contributing file got updated @DarkSoul26 @IbraheemHaseeb7

**Comment by DarkSoul26** [comment]
@anand346 please take a look into this
