### ISSUE TITLE
Typo : change content of right sidebar

### ISSUE THREAD

**Issue by anand346** [anand346/findissues#8]
change 'fav' and 'lang' on right sidebar to 'favourite' and 'language' and make it look professional

**Comment by AniketSaraswat112** [comment]
HI @anand346  would like to work on this issue.

**Comment by AniketSaraswat112** [comment]
I have provided a fix for this issue in [this PR](https://github.com/anand346/findissues/pull/10)

**Comment by iamkrishnagupta** [comment]
Hello, @anand346 I would like to fix this issue.
