### ISSUE TITLE
[FEATURE] Add sort to results

### ISSUE THREAD

**Issue by Yash636261** [anand346/findissues#92]
**Is your feature request related to a problem? Please describe.**
As of now, there is no option to sort the search results based on the number of stars.

**Describe the solution you'd like**
Adding a sorting feature, like what you see on GitHub, can make things easier and more user-friendly, solving problems and enhancing the experience.

**Additional context**
![image](https://github.com/anand346/findissues/assets/98970491/0d16648a-837b-4ee4-bec1-cdb43708c342)

**Comment by Yash-Ainapure** [comment]
Heyy,I would like to contribute but didn't get the where you want the changes.could you specify the things more/where the results thing is?

**Comment by Yash636261** [comment]
hii @Yash-Ainapure !! I would like to work on this issue, you can checkout the other open issues.

**Comment by anand346** [comment]
Hi @Yash636261, are you working on this issue?

**Comment by Yash636261** [comment]
yes, @anand346 i want to work on it can you assign it to me?

**Comment by Shashankpantiitbhilai** [comment]
assign it to me

**Comment by anand346** [comment]
Hi @Yash636261, I'm assigning this issue to you. Kindly raise a PR when you are done👍

**Comment by Yash636261** [comment]
> Hi @Yash636261, I'm assigning this issue to you. Kindly raise a PR when you are done👍

Sure, thanks.

**Comment by anand346** [comment]
Hi @Yash636261 #106 has a bug. Kindly take a look at the below video. When I click on any other language then the content is not changing according to that language. Kindly open a new PR after the bug fix. Thanks


https://github.com/anand346/findissues/assets/64061582/fc3e47f9-cdeb-4b57-bc43-21dac595a4a4

**Comment by Yash636261** [comment]
okay, I'll open a new pull request as soon as it's resolved. Thanks for bringing this to my attention!

**Comment by anand346** [comment]
Fixed in #110
